/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.co.swilson.advent;

import java.io.IOException;
import java.io.InputStream;

public class App {
    private static SolverFactory solverFactory = new SolverFactory();

    public static void main(String[] args) {
        System.out.println(args);
        if (args.length > 0) {
            var day = args[0];
            System.out.println("Running day " + day);
            try {
                InputStream is  = App.class.getClassLoader().getResourceAsStream("input" + day + ".txt");
                var input = new String(is.readAllBytes());
                var solver = solverFactory.forDay(day);

                var resultPartOne = solver.solvePartOne(input);
                System.out.println("Part 1:");
                System.out.println(resultPartOne);

                var resultPartTwo = solver.solvePartTwo(input);
                System.out.println("Part 2:");
                System.out.println(resultPartTwo);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("Specify a day to run");
        }
    }
}
